image: "rust:slim"

stages:
  - build
  - test
  - release

cargo-build:
  stage: build
  script:
    - cargo build

cargo-test:
  stage: test
  script:
    - rustc --version && cargo --version
    - cargo test --workspace --verbose

clippy-lint:
  stage: test
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy

build-release:
  stage: release
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/epl-gateway
      - target/release/epl-http
    expire_in: 1 week
