//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_setting")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub data_version: i64,
    pub inbox_current_tab: i32,
    pub inbox_viewed_tutorial: bool,
    pub user_content_dismissed: Option<Vec<i16>>,
    pub voice_video_background_blur: bool,
    pub voice_video_always_preview: bool,
    pub voice_video_preset_option: i32,
    pub voice_afk_timeout: i32,
    pub voice_stream_notifications_enabled: bool,
    pub voice_native_phone_integration_enabled: bool,
    pub text_use_rich_chat_input: bool,
    pub text_use_thread_sidebar: bool,
    pub text_render_spoilers: String,
    pub text_emoji_picker_collapsed_sections: Vec<String>,
    pub text_sticker_picker_collapsed_sections: Vec<String>,
    pub text_view_image_descriptions: bool,
    pub text_show_command_suggestions: bool,
    pub text_inline_attachment_media: bool,
    pub text_inline_embed_media: bool,
    pub text_gif_auto_play: bool,
    pub text_render_embeds: bool,
    pub text_render_reactions: bool,
    pub text_animate_emoji: bool,
    pub text_animate_stickers: i32,
    pub text_enable_tts_command: bool,
    pub text_message_display_compact: bool,
    pub text_explicit_content_filter: i32,
    pub text_view_nsfw_guilds: bool,
    pub text_convert_emoticons: bool,
    pub text_expression_suggestions_enabled: bool,
    pub text_view_nsfw_commands: bool,
    pub notification_show_in_app_notifications: bool,
    pub notification_notify_friends_on_go_live: bool,
    pub privacy_allow_activity_party_privacy_friends: bool,
    pub privacy_allow_activity_party_privacy_voice_channel: bool,
    pub privacy_restricted_guild_ids: Option<Vec<i64>>,
    pub privacy_default_guilds_restricted: bool,
    pub privacy_allow_accessibility_detection: bool,
    pub privacy_detect_platform_accounts: bool,
    pub privacy_contact_sync_enabled: bool,
    pub privacy_friend_source_flags: i32,
    pub privacy_friend_discovery_flags: i32,
    pub privacy_activity_restricted_guild_ids: Option<Vec<i64>>,
    pub privacy_guild_activity_status_restriction_default: i32,
    pub privacy_activity_joining_restricted_guild_ids: Option<Vec<i64>>,
    pub debug_rtc_panel_show_voice_states: bool,
    pub game_library_install_shortcut_desktop: bool,
    pub game_library_install_shortcut_start_menu: bool,
    pub game_library_disable_games_tab: bool,
    pub localization_locale: String,
    pub localization_timezone_offset: i32,
    pub appearance_theme: i32,
    pub appearance_developer_mode: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::User",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
